### ISSUE TITLE
Typo in chapter 00 line 375 - wrong file name

### ISSUE THREAD

**Issue by sportfloh** [vanvoorden/TDD-Albums-II#1]
hey,
thanks for the great tutorial!

Line 375 of chapter 00 is:
//  NetworkDataHandlerTests.swift
but it should be:
//  NetworkDataHandler.swift
Cheers!

**Comment by vanvoorden** [comment]
https://github.com/vanvoorden/TDD-Albums-II/wiki/Chapter-00:-Network-Data-Handler/_compare/69b445a4e24edd2c2abc31b37f5ecf736da2cd51...af002af621f57e6725d4bb7ae7017edb5b82846d

Thanks! That was a bug in the documentation. The fix has landed. Thanks for opening the issue!
