### ISSUE TITLE
Wrong file name in chapter 03 on line 162

### ISSUE THREAD

**Issue by sportfloh** [vanvoorden/TDD-Albums-II#3]
NetworkImageSerializationTests.swift should be NetworkImageSerialization.swift

**Comment by vanvoorden** [comment]
https://github.com/vanvoorden/TDD-Albums-II/wiki/Chapter-03:-Network-Image-Serialization/_compare/25a3dab7dc25b6e41986067a4430d6669d6212d3...38ce9f0094c6948297f34aa8bf9fd12b7c0d5d34

Ahh. You are correct! That is an error. I landed a fix. Thank you for opening an issue!
